name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with: 
          python-version: "3.10"
      - name: Installation of dependencies
        run: | 
          pip install --upgrade pip
          pip install -U -r requirements.txt
      - name: Deploy Logs 
        run: python autocast.py
